name: CI

on: push

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    environment: test
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: core_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v3

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14' # Define the elixir version [required]
        otp-version: '25.0' # Define the OTP version [required]

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get
      
    - name: Checks unused dependencies
      run: mix deps.unlock --check-unused

    - name: Check warnings
      run: mix compile --warning-as-errors

    - name: Check formatting
      run: mix format --check-formatted

    - name: Check code smells
      run: mix credo --strict

    - name: Run tests
      run: mix test --warnings-as-errors
